# أسرار التطبيق — لا تُرفع إلى Git إطلاقًا (انظر .gitignore)
SUPABASE_URL=https://tbnwlsucgfcpwajerjuw.supabase.co
SUPABASE_ANON_KEY=sb_publishable_7Ag4mo1vX7jpLvOxeUV_wQ_w4UHz-9Q
NEWSDATA_API_KEY=pub_e2c9d11a488a4c80a64359bc93ae35c6
GOOGLE_WEB_CLIENT_ID=872343695367-19gvum3637gp9801o2gnfi1d1gjvpve0.apps.googleusercontent.com
GEMINI_API_KEY=AQ.Ab8RN6K3bpeiHDZb-JqtYpuJ3Q1sSln13jbMie9p4LYwaDs9MA
